/* soapTmriJaxRpcOutAccessServiceSoapProxy.cpp
   Generated by gSOAP 2.8.14 from TmriOutAccess.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapTmriJaxRpcOutAccessServiceSoapProxy.h"

TmriJaxRpcOutAccessServiceSoapProxy::TmriJaxRpcOutAccessServiceSoapProxy()
{	TmriJaxRpcOutAccessServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

TmriJaxRpcOutAccessServiceSoapProxy::TmriJaxRpcOutAccessServiceSoapProxy(const struct soap &_soap) : soap(_soap)
{ }

TmriJaxRpcOutAccessServiceSoapProxy::TmriJaxRpcOutAccessServiceSoapProxy(const char *url)
{	TmriJaxRpcOutAccessServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

TmriJaxRpcOutAccessServiceSoapProxy::TmriJaxRpcOutAccessServiceSoapProxy(soap_mode iomode)
{	TmriJaxRpcOutAccessServiceSoapProxy_init(iomode, iomode);
}

TmriJaxRpcOutAccessServiceSoapProxy::TmriJaxRpcOutAccessServiceSoapProxy(const char *url, soap_mode iomode)
{	TmriJaxRpcOutAccessServiceSoapProxy_init(iomode, iomode);
	soap_endpoint = url;
}

TmriJaxRpcOutAccessServiceSoapProxy::TmriJaxRpcOutAccessServiceSoapProxy(soap_mode imode, soap_mode omode)
{	TmriJaxRpcOutAccessServiceSoapProxy_init(imode, omode);
}

TmriJaxRpcOutAccessServiceSoapProxy::~TmriJaxRpcOutAccessServiceSoapProxy()
{ }

void TmriJaxRpcOutAccessServiceSoapProxy::TmriJaxRpcOutAccessServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void TmriJaxRpcOutAccessServiceSoapProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void TmriJaxRpcOutAccessServiceSoapProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	TmriJaxRpcOutAccessServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void TmriJaxRpcOutAccessServiceSoapProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *TmriJaxRpcOutAccessServiceSoapProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *TmriJaxRpcOutAccessServiceSoapProxy::soap_fault()
{	return this->fault;
}

const char *TmriJaxRpcOutAccessServiceSoapProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *TmriJaxRpcOutAccessServiceSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int TmriJaxRpcOutAccessServiceSoapProxy::soap_close_socket()
{	return soap_closesock(this);
}

int TmriJaxRpcOutAccessServiceSoapProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void TmriJaxRpcOutAccessServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void TmriJaxRpcOutAccessServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *TmriJaxRpcOutAccessServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int TmriJaxRpcOutAccessServiceSoapProxy::queryObjectOut(const char *endpoint, const char *soap_action, _ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse *ns1__queryObjectOutResponse)
{	struct soap *soap = this;
	struct __ns1__queryObjectOut soap_tmp___ns1__queryObjectOut;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.1.2.38/jcxws/TmriOutAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/queryObjectOut";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__queryObjectOut.ns1__queryObjectOut = ns1__queryObjectOut;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__queryObjectOut(soap, &soap_tmp___ns1__queryObjectOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__queryObjectOut(soap, &soap_tmp___ns1__queryObjectOut, "-ns1:queryObjectOut", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__queryObjectOut(soap, &soap_tmp___ns1__queryObjectOut, "-ns1:queryObjectOut", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__queryObjectOutResponse)
		return soap_closesock(soap);
	ns1__queryObjectOutResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__queryObjectOutResponse->soap_get(soap, "ns1:queryObjectOutResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TmriJaxRpcOutAccessServiceSoapProxy::writeObjectOut(const char *endpoint, const char *soap_action, _ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse *ns1__writeObjectOutResponse)
{	struct soap *soap = this;
	struct __ns1__writeObjectOut soap_tmp___ns1__writeObjectOut;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.1.2.38/jcxws/TmriOutAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/writeObjectOut";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__writeObjectOut.ns1__writeObjectOut = ns1__writeObjectOut;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__writeObjectOut(soap, &soap_tmp___ns1__writeObjectOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__writeObjectOut(soap, &soap_tmp___ns1__writeObjectOut, "-ns1:writeObjectOut", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__writeObjectOut(soap, &soap_tmp___ns1__writeObjectOut, "-ns1:writeObjectOut", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__writeObjectOutResponse)
		return soap_closesock(soap);
	ns1__writeObjectOutResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__writeObjectOutResponse->soap_get(soap, "ns1:writeObjectOutResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TmriJaxRpcOutAccessServiceSoapProxy::queryObjectOut_(const char *endpoint, const char *soap_action, _ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse *ns1__queryObjectOutResponse)
{	struct soap *soap = this;
	struct __ns1__queryObjectOut_ soap_tmp___ns1__queryObjectOut_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.1.2.38/jcxws/TmriOutAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/queryObjectOut";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__queryObjectOut_.ns1__queryObjectOut = ns1__queryObjectOut;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__queryObjectOut_(soap, &soap_tmp___ns1__queryObjectOut_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__queryObjectOut_(soap, &soap_tmp___ns1__queryObjectOut_, "-ns1:queryObjectOut", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__queryObjectOut_(soap, &soap_tmp___ns1__queryObjectOut_, "-ns1:queryObjectOut", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__queryObjectOutResponse)
		return soap_closesock(soap);
	ns1__queryObjectOutResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__queryObjectOutResponse->soap_get(soap, "ns1:queryObjectOutResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TmriJaxRpcOutAccessServiceSoapProxy::writeObjectOut_(const char *endpoint, const char *soap_action, _ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse *ns1__writeObjectOutResponse)
{	struct soap *soap = this;
	struct __ns1__writeObjectOut_ soap_tmp___ns1__writeObjectOut_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.1.2.38/jcxws/TmriOutAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/writeObjectOut";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__writeObjectOut_.ns1__writeObjectOut = ns1__writeObjectOut;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__writeObjectOut_(soap, &soap_tmp___ns1__writeObjectOut_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__writeObjectOut_(soap, &soap_tmp___ns1__writeObjectOut_, "-ns1:writeObjectOut", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__writeObjectOut_(soap, &soap_tmp___ns1__writeObjectOut_, "-ns1:writeObjectOut", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__writeObjectOutResponse)
		return soap_closesock(soap);
	ns1__writeObjectOutResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__writeObjectOutResponse->soap_get(soap, "ns1:writeObjectOutResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
