/* soapH.h
   Generated by gSOAP 2.8.14 from TmriOutAccess.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin(soap), soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin(soap), soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_std__wstring
#define SOAP_TYPE_std__wstring (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__wstring(struct soap*, std::wstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__wstring(struct soap*, const std::wstring *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__wstring(struct soap*, const char*, int, const std::wstring*, const char*);
SOAP_FMAC3 std::wstring * SOAP_FMAC4 soap_in_std__wstring(struct soap*, const char*, std::wstring*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__wstring(struct soap*, const std::wstring *, const char*, const char*);

#ifndef soap_write_std__wstring
#define soap_write_std__wstring(soap, data) ( soap_begin(soap), soap_serialize_std__wstring(soap, data), soap_begin_send(soap) || soap_put_std__wstring(soap, data, "string", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 std::wstring * SOAP_FMAC4 soap_get_std__wstring(struct soap*, std::wstring *, const char*, const char*);

#ifndef soap_read_std__wstring
#define soap_read_std__wstring(soap, data) ( soap_begin_recv(soap) || !soap_get_std__wstring(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 std::wstring * SOAP_FMAC2 soap_instantiate_std__wstring(struct soap*, int, const char*, const char*, size_t*);

inline std::wstring * soap_new_std__wstring(struct soap *soap, int n = -1) { return soap_instantiate_std__wstring(soap, n, NULL, NULL, NULL); }

inline std::wstring * soap_new_req_std__wstring(struct soap *soap) { std::wstring *_p = soap_instantiate_std__wstring(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__wstring(soap, _p); } return _p; }

inline std::wstring * soap_new_set_std__wstring(struct soap *soap) { std::wstring *_p = soap_instantiate_std__wstring(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__wstring(soap, _p); } return _p; }

inline void soap_delete_std__wstring(struct soap *soap, std::wstring *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__wstring(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__writeObjectOutResponse
#define SOAP_TYPE__ns1__writeObjectOutResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__writeObjectOutResponse(struct soap*, const char*, int, const _ns1__writeObjectOutResponse *, const char*);
SOAP_FMAC3 _ns1__writeObjectOutResponse * SOAP_FMAC4 soap_in__ns1__writeObjectOutResponse(struct soap*, const char*, _ns1__writeObjectOutResponse *, const char*);

#ifndef soap_write__ns1__writeObjectOutResponse
#define soap_write__ns1__writeObjectOutResponse(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:writeObjectOutResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__writeObjectOutResponse * SOAP_FMAC4 soap_get__ns1__writeObjectOutResponse(struct soap*, _ns1__writeObjectOutResponse *, const char*, const char*);

#ifndef soap_read__ns1__writeObjectOutResponse
#define soap_read__ns1__writeObjectOutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__writeObjectOutResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns1__writeObjectOutResponse * SOAP_FMAC2 soap_instantiate__ns1__writeObjectOutResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__writeObjectOutResponse * soap_new__ns1__writeObjectOutResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__writeObjectOutResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__writeObjectOutResponse * soap_new_req__ns1__writeObjectOutResponse(struct soap *soap) { _ns1__writeObjectOutResponse *_p = soap_instantiate__ns1__writeObjectOutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__writeObjectOutResponse * soap_new_set__ns1__writeObjectOutResponse(struct soap *soap, std::wstring *writeObjectOutResult) { _ns1__writeObjectOutResponse *_p = soap_instantiate__ns1__writeObjectOutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__writeObjectOutResponse::writeObjectOutResult = writeObjectOutResult; } return _p; }

inline void soap_delete__ns1__writeObjectOutResponse(struct soap *soap, _ns1__writeObjectOutResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__writeObjectOutResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__writeObjectOut
#define SOAP_TYPE__ns1__writeObjectOut (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__writeObjectOut(struct soap*, const char*, int, const _ns1__writeObjectOut *, const char*);
SOAP_FMAC3 _ns1__writeObjectOut * SOAP_FMAC4 soap_in__ns1__writeObjectOut(struct soap*, const char*, _ns1__writeObjectOut *, const char*);

#ifndef soap_write__ns1__writeObjectOut
#define soap_write__ns1__writeObjectOut(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:writeObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__writeObjectOut * SOAP_FMAC4 soap_get__ns1__writeObjectOut(struct soap*, _ns1__writeObjectOut *, const char*, const char*);

#ifndef soap_read__ns1__writeObjectOut
#define soap_read__ns1__writeObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__writeObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns1__writeObjectOut * SOAP_FMAC2 soap_instantiate__ns1__writeObjectOut(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__writeObjectOut * soap_new__ns1__writeObjectOut(struct soap *soap, int n = -1) { return soap_instantiate__ns1__writeObjectOut(soap, n, NULL, NULL, NULL); }

inline _ns1__writeObjectOut * soap_new_req__ns1__writeObjectOut(struct soap *soap) { _ns1__writeObjectOut *_p = soap_instantiate__ns1__writeObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__writeObjectOut * soap_new_set__ns1__writeObjectOut(struct soap *soap, std::wstring *xtlb, std::wstring *jkxlh, std::wstring *jkid, std::wstring *WriteXmlDoc) { _ns1__writeObjectOut *_p = soap_instantiate__ns1__writeObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__writeObjectOut::xtlb = xtlb; _p->_ns1__writeObjectOut::jkxlh = jkxlh; _p->_ns1__writeObjectOut::jkid = jkid; _p->_ns1__writeObjectOut::WriteXmlDoc = WriteXmlDoc; } return _p; }

inline void soap_delete__ns1__writeObjectOut(struct soap *soap, _ns1__writeObjectOut *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__writeObjectOut(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__queryObjectOutResponse
#define SOAP_TYPE__ns1__queryObjectOutResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__queryObjectOutResponse(struct soap*, const char*, int, const _ns1__queryObjectOutResponse *, const char*);
SOAP_FMAC3 _ns1__queryObjectOutResponse * SOAP_FMAC4 soap_in__ns1__queryObjectOutResponse(struct soap*, const char*, _ns1__queryObjectOutResponse *, const char*);

#ifndef soap_write__ns1__queryObjectOutResponse
#define soap_write__ns1__queryObjectOutResponse(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:queryObjectOutResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__queryObjectOutResponse * SOAP_FMAC4 soap_get__ns1__queryObjectOutResponse(struct soap*, _ns1__queryObjectOutResponse *, const char*, const char*);

#ifndef soap_read__ns1__queryObjectOutResponse
#define soap_read__ns1__queryObjectOutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__queryObjectOutResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns1__queryObjectOutResponse * SOAP_FMAC2 soap_instantiate__ns1__queryObjectOutResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__queryObjectOutResponse * soap_new__ns1__queryObjectOutResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__queryObjectOutResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__queryObjectOutResponse * soap_new_req__ns1__queryObjectOutResponse(struct soap *soap) { _ns1__queryObjectOutResponse *_p = soap_instantiate__ns1__queryObjectOutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__queryObjectOutResponse * soap_new_set__ns1__queryObjectOutResponse(struct soap *soap, std::wstring *queryObjectOutResult) { _ns1__queryObjectOutResponse *_p = soap_instantiate__ns1__queryObjectOutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__queryObjectOutResponse::queryObjectOutResult = queryObjectOutResult; } return _p; }

inline void soap_delete__ns1__queryObjectOutResponse(struct soap *soap, _ns1__queryObjectOutResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__queryObjectOutResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__queryObjectOut
#define SOAP_TYPE__ns1__queryObjectOut (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__queryObjectOut(struct soap*, const char*, int, const _ns1__queryObjectOut *, const char*);
SOAP_FMAC3 _ns1__queryObjectOut * SOAP_FMAC4 soap_in__ns1__queryObjectOut(struct soap*, const char*, _ns1__queryObjectOut *, const char*);

#ifndef soap_write__ns1__queryObjectOut
#define soap_write__ns1__queryObjectOut(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:queryObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__queryObjectOut * SOAP_FMAC4 soap_get__ns1__queryObjectOut(struct soap*, _ns1__queryObjectOut *, const char*, const char*);

#ifndef soap_read__ns1__queryObjectOut
#define soap_read__ns1__queryObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__queryObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns1__queryObjectOut * SOAP_FMAC2 soap_instantiate__ns1__queryObjectOut(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__queryObjectOut * soap_new__ns1__queryObjectOut(struct soap *soap, int n = -1) { return soap_instantiate__ns1__queryObjectOut(soap, n, NULL, NULL, NULL); }

inline _ns1__queryObjectOut * soap_new_req__ns1__queryObjectOut(struct soap *soap) { _ns1__queryObjectOut *_p = soap_instantiate__ns1__queryObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__queryObjectOut * soap_new_set__ns1__queryObjectOut(struct soap *soap, std::wstring *xtlb, std::wstring *jkxlh, std::wstring *jkid, std::wstring *QueryXmlDoc) { _ns1__queryObjectOut *_p = soap_instantiate__ns1__queryObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__queryObjectOut::xtlb = xtlb; _p->_ns1__queryObjectOut::jkxlh = jkxlh; _p->_ns1__queryObjectOut::jkid = jkid; _p->_ns1__queryObjectOut::QueryXmlDoc = QueryXmlDoc; } return _p; }

inline void soap_delete__ns1__queryObjectOut(struct soap *soap, _ns1__queryObjectOut *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__queryObjectOut(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__writeObjectOut_
#define SOAP_TYPE___ns1__writeObjectOut_ (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__writeObjectOut_(struct soap*, struct __ns1__writeObjectOut_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__writeObjectOut_(struct soap*, const struct __ns1__writeObjectOut_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__writeObjectOut_(struct soap*, const char*, int, const struct __ns1__writeObjectOut_ *, const char*);
SOAP_FMAC3 struct __ns1__writeObjectOut_ * SOAP_FMAC4 soap_in___ns1__writeObjectOut_(struct soap*, const char*, struct __ns1__writeObjectOut_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__writeObjectOut_(struct soap*, const struct __ns1__writeObjectOut_ *, const char*, const char*);

#ifndef soap_write___ns1__writeObjectOut_
#define soap_write___ns1__writeObjectOut_(soap, data) ( soap_begin(soap), soap_serialize___ns1__writeObjectOut_(soap, data), soap_begin_send(soap) || soap_put___ns1__writeObjectOut_(soap, data, "-ns1:writeObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__writeObjectOut_ * SOAP_FMAC4 soap_get___ns1__writeObjectOut_(struct soap*, struct __ns1__writeObjectOut_ *, const char*, const char*);

#ifndef soap_read___ns1__writeObjectOut_
#define soap_read___ns1__writeObjectOut_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__writeObjectOut_(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__writeObjectOut_ * SOAP_FMAC2 soap_instantiate___ns1__writeObjectOut_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__writeObjectOut_ * soap_new___ns1__writeObjectOut_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__writeObjectOut_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__writeObjectOut_ * soap_new_req___ns1__writeObjectOut_(struct soap *soap) { struct __ns1__writeObjectOut_ *_p = soap_instantiate___ns1__writeObjectOut_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__writeObjectOut_(soap, _p); } return _p; }

inline struct __ns1__writeObjectOut_ * soap_new_set___ns1__writeObjectOut_(struct soap *soap, _ns1__writeObjectOut *ns1__writeObjectOut) { struct __ns1__writeObjectOut_ *_p = soap_instantiate___ns1__writeObjectOut_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__writeObjectOut_(soap, _p); _p->ns1__writeObjectOut = ns1__writeObjectOut; } return _p; }

inline void soap_delete___ns1__writeObjectOut_(struct soap *soap, struct __ns1__writeObjectOut_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__writeObjectOut_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__queryObjectOut_
#define SOAP_TYPE___ns1__queryObjectOut_ (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__queryObjectOut_(struct soap*, struct __ns1__queryObjectOut_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__queryObjectOut_(struct soap*, const struct __ns1__queryObjectOut_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__queryObjectOut_(struct soap*, const char*, int, const struct __ns1__queryObjectOut_ *, const char*);
SOAP_FMAC3 struct __ns1__queryObjectOut_ * SOAP_FMAC4 soap_in___ns1__queryObjectOut_(struct soap*, const char*, struct __ns1__queryObjectOut_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__queryObjectOut_(struct soap*, const struct __ns1__queryObjectOut_ *, const char*, const char*);

#ifndef soap_write___ns1__queryObjectOut_
#define soap_write___ns1__queryObjectOut_(soap, data) ( soap_begin(soap), soap_serialize___ns1__queryObjectOut_(soap, data), soap_begin_send(soap) || soap_put___ns1__queryObjectOut_(soap, data, "-ns1:queryObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__queryObjectOut_ * SOAP_FMAC4 soap_get___ns1__queryObjectOut_(struct soap*, struct __ns1__queryObjectOut_ *, const char*, const char*);

#ifndef soap_read___ns1__queryObjectOut_
#define soap_read___ns1__queryObjectOut_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__queryObjectOut_(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__queryObjectOut_ * SOAP_FMAC2 soap_instantiate___ns1__queryObjectOut_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__queryObjectOut_ * soap_new___ns1__queryObjectOut_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__queryObjectOut_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__queryObjectOut_ * soap_new_req___ns1__queryObjectOut_(struct soap *soap) { struct __ns1__queryObjectOut_ *_p = soap_instantiate___ns1__queryObjectOut_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__queryObjectOut_(soap, _p); } return _p; }

inline struct __ns1__queryObjectOut_ * soap_new_set___ns1__queryObjectOut_(struct soap *soap, _ns1__queryObjectOut *ns1__queryObjectOut) { struct __ns1__queryObjectOut_ *_p = soap_instantiate___ns1__queryObjectOut_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__queryObjectOut_(soap, _p); _p->ns1__queryObjectOut = ns1__queryObjectOut; } return _p; }

inline void soap_delete___ns1__queryObjectOut_(struct soap *soap, struct __ns1__queryObjectOut_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__queryObjectOut_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__writeObjectOut
#define SOAP_TYPE___ns1__writeObjectOut (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__writeObjectOut(struct soap*, struct __ns1__writeObjectOut *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__writeObjectOut(struct soap*, const struct __ns1__writeObjectOut *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__writeObjectOut(struct soap*, const char*, int, const struct __ns1__writeObjectOut *, const char*);
SOAP_FMAC3 struct __ns1__writeObjectOut * SOAP_FMAC4 soap_in___ns1__writeObjectOut(struct soap*, const char*, struct __ns1__writeObjectOut *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__writeObjectOut(struct soap*, const struct __ns1__writeObjectOut *, const char*, const char*);

#ifndef soap_write___ns1__writeObjectOut
#define soap_write___ns1__writeObjectOut(soap, data) ( soap_begin(soap), soap_serialize___ns1__writeObjectOut(soap, data), soap_begin_send(soap) || soap_put___ns1__writeObjectOut(soap, data, "-ns1:writeObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__writeObjectOut * SOAP_FMAC4 soap_get___ns1__writeObjectOut(struct soap*, struct __ns1__writeObjectOut *, const char*, const char*);

#ifndef soap_read___ns1__writeObjectOut
#define soap_read___ns1__writeObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__writeObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__writeObjectOut * SOAP_FMAC2 soap_instantiate___ns1__writeObjectOut(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__writeObjectOut * soap_new___ns1__writeObjectOut(struct soap *soap, int n = -1) { return soap_instantiate___ns1__writeObjectOut(soap, n, NULL, NULL, NULL); }

inline struct __ns1__writeObjectOut * soap_new_req___ns1__writeObjectOut(struct soap *soap) { struct __ns1__writeObjectOut *_p = soap_instantiate___ns1__writeObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__writeObjectOut(soap, _p); } return _p; }

inline struct __ns1__writeObjectOut * soap_new_set___ns1__writeObjectOut(struct soap *soap, _ns1__writeObjectOut *ns1__writeObjectOut) { struct __ns1__writeObjectOut *_p = soap_instantiate___ns1__writeObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__writeObjectOut(soap, _p); _p->ns1__writeObjectOut = ns1__writeObjectOut; } return _p; }

inline void soap_delete___ns1__writeObjectOut(struct soap *soap, struct __ns1__writeObjectOut *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__writeObjectOut(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__queryObjectOut
#define SOAP_TYPE___ns1__queryObjectOut (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__queryObjectOut(struct soap*, struct __ns1__queryObjectOut *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__queryObjectOut(struct soap*, const struct __ns1__queryObjectOut *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__queryObjectOut(struct soap*, const char*, int, const struct __ns1__queryObjectOut *, const char*);
SOAP_FMAC3 struct __ns1__queryObjectOut * SOAP_FMAC4 soap_in___ns1__queryObjectOut(struct soap*, const char*, struct __ns1__queryObjectOut *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__queryObjectOut(struct soap*, const struct __ns1__queryObjectOut *, const char*, const char*);

#ifndef soap_write___ns1__queryObjectOut
#define soap_write___ns1__queryObjectOut(soap, data) ( soap_begin(soap), soap_serialize___ns1__queryObjectOut(soap, data), soap_begin_send(soap) || soap_put___ns1__queryObjectOut(soap, data, "-ns1:queryObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__queryObjectOut * SOAP_FMAC4 soap_get___ns1__queryObjectOut(struct soap*, struct __ns1__queryObjectOut *, const char*, const char*);

#ifndef soap_read___ns1__queryObjectOut
#define soap_read___ns1__queryObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__queryObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__queryObjectOut * SOAP_FMAC2 soap_instantiate___ns1__queryObjectOut(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__queryObjectOut * soap_new___ns1__queryObjectOut(struct soap *soap, int n = -1) { return soap_instantiate___ns1__queryObjectOut(soap, n, NULL, NULL, NULL); }

inline struct __ns1__queryObjectOut * soap_new_req___ns1__queryObjectOut(struct soap *soap) { struct __ns1__queryObjectOut *_p = soap_instantiate___ns1__queryObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__queryObjectOut(soap, _p); } return _p; }

inline struct __ns1__queryObjectOut * soap_new_set___ns1__queryObjectOut(struct soap *soap, _ns1__queryObjectOut *ns1__queryObjectOut) { struct __ns1__queryObjectOut *_p = soap_instantiate___ns1__queryObjectOut(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__queryObjectOut(soap, _p); _p->ns1__queryObjectOut = ns1__queryObjectOut; } return _p; }

inline void soap_delete___ns1__queryObjectOut(struct soap *soap, struct __ns1__queryObjectOut *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__queryObjectOut(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__writeObjectOutResponse
#define SOAP_TYPE_PointerTo_ns1__writeObjectOutResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__writeObjectOutResponse(struct soap*, _ns1__writeObjectOutResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__writeObjectOutResponse(struct soap*, const char *, int, _ns1__writeObjectOutResponse *const*, const char *);
SOAP_FMAC3 _ns1__writeObjectOutResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__writeObjectOutResponse(struct soap*, const char*, _ns1__writeObjectOutResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__writeObjectOutResponse(struct soap*, _ns1__writeObjectOutResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__writeObjectOutResponse
#define soap_write_PointerTo_ns1__writeObjectOutResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__writeObjectOutResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__writeObjectOutResponse(soap, data, "ns1:writeObjectOutResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__writeObjectOutResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__writeObjectOutResponse(struct soap*, _ns1__writeObjectOutResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__writeObjectOutResponse
#define soap_read_PointerTo_ns1__writeObjectOutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__writeObjectOutResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__writeObjectOut
#define SOAP_TYPE_PointerTo_ns1__writeObjectOut (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__writeObjectOut(struct soap*, _ns1__writeObjectOut *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__writeObjectOut(struct soap*, const char *, int, _ns1__writeObjectOut *const*, const char *);
SOAP_FMAC3 _ns1__writeObjectOut ** SOAP_FMAC4 soap_in_PointerTo_ns1__writeObjectOut(struct soap*, const char*, _ns1__writeObjectOut **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__writeObjectOut(struct soap*, _ns1__writeObjectOut *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__writeObjectOut
#define soap_write_PointerTo_ns1__writeObjectOut(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__writeObjectOut(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__writeObjectOut(soap, data, "ns1:writeObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__writeObjectOut ** SOAP_FMAC4 soap_get_PointerTo_ns1__writeObjectOut(struct soap*, _ns1__writeObjectOut **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__writeObjectOut
#define soap_read_PointerTo_ns1__writeObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__writeObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__queryObjectOutResponse
#define SOAP_TYPE_PointerTo_ns1__queryObjectOutResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__queryObjectOutResponse(struct soap*, _ns1__queryObjectOutResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__queryObjectOutResponse(struct soap*, const char *, int, _ns1__queryObjectOutResponse *const*, const char *);
SOAP_FMAC3 _ns1__queryObjectOutResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__queryObjectOutResponse(struct soap*, const char*, _ns1__queryObjectOutResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__queryObjectOutResponse(struct soap*, _ns1__queryObjectOutResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__queryObjectOutResponse
#define soap_write_PointerTo_ns1__queryObjectOutResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__queryObjectOutResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__queryObjectOutResponse(soap, data, "ns1:queryObjectOutResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__queryObjectOutResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__queryObjectOutResponse(struct soap*, _ns1__queryObjectOutResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__queryObjectOutResponse
#define soap_read_PointerTo_ns1__queryObjectOutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__queryObjectOutResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__queryObjectOut
#define SOAP_TYPE_PointerTo_ns1__queryObjectOut (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__queryObjectOut(struct soap*, _ns1__queryObjectOut *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__queryObjectOut(struct soap*, const char *, int, _ns1__queryObjectOut *const*, const char *);
SOAP_FMAC3 _ns1__queryObjectOut ** SOAP_FMAC4 soap_in_PointerTo_ns1__queryObjectOut(struct soap*, const char*, _ns1__queryObjectOut **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__queryObjectOut(struct soap*, _ns1__queryObjectOut *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__queryObjectOut
#define soap_write_PointerTo_ns1__queryObjectOut(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__queryObjectOut(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__queryObjectOut(soap, data, "ns1:queryObjectOut", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns1__queryObjectOut ** SOAP_FMAC4 soap_get_PointerTo_ns1__queryObjectOut(struct soap*, _ns1__queryObjectOut **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__queryObjectOut
#define soap_read_PointerTo_ns1__queryObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__queryObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTostd__wstring
#define SOAP_TYPE_PointerTostd__wstring (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__wstring(struct soap*, std::wstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__wstring(struct soap*, const char *, int, std::wstring *const*, const char *);
SOAP_FMAC3 std::wstring ** SOAP_FMAC4 soap_in_PointerTostd__wstring(struct soap*, const char*, std::wstring **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__wstring(struct soap*, std::wstring *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__wstring
#define soap_write_PointerTostd__wstring(soap, data) ( soap_begin(soap), soap_serialize_PointerTostd__wstring(soap, data), soap_begin_send(soap) || soap_put_PointerTostd__wstring(soap, data, "string", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 std::wstring ** SOAP_FMAC4 soap_get_PointerTostd__wstring(struct soap*, std::wstring **, const char*, const char*);

#ifndef soap_read_PointerTostd__wstring
#define soap_read_PointerTostd__wstring(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__wstring(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin(soap), soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin(soap), soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

/* End of soapH.h */
