/* soapTmriOutAccessSoapProxy.h
   Generated by gSOAP 2.8.21 from TmriOutAccess.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapTmriOutAccessSoapProxy_H
#define soapTmriOutAccessSoapProxy_H
#include "soapH.h"

class SOAP_CMAC TmriOutAccessSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'TmriOutAccessSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in TmriOutAccess.h (non-static)
	/// Constructor
	TmriOutAccessSoapProxy();
	/// Construct from another engine state
	TmriOutAccessSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	TmriOutAccessSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	TmriOutAccessSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	TmriOutAccessSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	TmriOutAccessSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~TmriOutAccessSoapProxy();
	/// Initializer used by constructors
	virtual	void TmriOutAccessSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetVer' (returns error code or SOAP_OK)
	virtual	int GetVer(_ns1__GetVer *ns1__GetVer, _ns1__GetVerResponse &ns1__GetVerResponse) { return this->GetVer(NULL, NULL, ns1__GetVer, ns1__GetVerResponse); }
	virtual	int GetVer(const char *endpoint, const char *soap_action, _ns1__GetVer *ns1__GetVer, _ns1__GetVerResponse &ns1__GetVerResponse);

	/// Web service operation 'queryObjectOut' (returns error code or SOAP_OK)
	virtual	int queryObjectOut(_ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse) { return this->queryObjectOut(NULL, NULL, ns1__queryObjectOut, ns1__queryObjectOutResponse); }
	virtual	int queryObjectOut(const char *endpoint, const char *soap_action, _ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse);

	/// Web service operation 'writeObjectOut' (returns error code or SOAP_OK)
	virtual	int writeObjectOut(_ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse) { return this->writeObjectOut(NULL, NULL, ns1__writeObjectOut, ns1__writeObjectOutResponse); }
	virtual	int writeObjectOut(const char *endpoint, const char *soap_action, _ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse);

	/// Web service operation 'NetworkingQueryObjectOut' (returns error code or SOAP_OK)
	virtual	int NetworkingQueryObjectOut(_ns1__NetworkingQueryObjectOut *ns1__NetworkingQueryObjectOut, _ns1__NetworkingQueryObjectOutResponse &ns1__NetworkingQueryObjectOutResponse) { return this->NetworkingQueryObjectOut(NULL, NULL, ns1__NetworkingQueryObjectOut, ns1__NetworkingQueryObjectOutResponse); }
	virtual	int NetworkingQueryObjectOut(const char *endpoint, const char *soap_action, _ns1__NetworkingQueryObjectOut *ns1__NetworkingQueryObjectOut, _ns1__NetworkingQueryObjectOutResponse &ns1__NetworkingQueryObjectOutResponse);

	/// Web service operation 'NetworkingWriteObjectOut' (returns error code or SOAP_OK)
	virtual	int NetworkingWriteObjectOut(_ns1__NetworkingWriteObjectOut *ns1__NetworkingWriteObjectOut, _ns1__NetworkingWriteObjectOutResponse &ns1__NetworkingWriteObjectOutResponse) { return this->NetworkingWriteObjectOut(NULL, NULL, ns1__NetworkingWriteObjectOut, ns1__NetworkingWriteObjectOutResponse); }
	virtual	int NetworkingWriteObjectOut(const char *endpoint, const char *soap_action, _ns1__NetworkingWriteObjectOut *ns1__NetworkingWriteObjectOut, _ns1__NetworkingWriteObjectOutResponse &ns1__NetworkingWriteObjectOutResponse);

	/// Web service operation 'GetLoginParm' (returns error code or SOAP_OK)
	virtual	int GetLoginParm(_ns1__GetLoginParm *ns1__GetLoginParm, _ns1__GetLoginParmResponse &ns1__GetLoginParmResponse) { return this->GetLoginParm(NULL, NULL, ns1__GetLoginParm, ns1__GetLoginParmResponse); }
	virtual	int GetLoginParm(const char *endpoint, const char *soap_action, _ns1__GetLoginParm *ns1__GetLoginParm, _ns1__GetLoginParmResponse &ns1__GetLoginParmResponse);

	/// Web service operation 'zjqueryObjectOut' (returns error code or SOAP_OK)
	virtual	int zjqueryObjectOut(_ns1__zjqueryObjectOut *ns1__zjqueryObjectOut, _ns1__zjqueryObjectOutResponse &ns1__zjqueryObjectOutResponse) { return this->zjqueryObjectOut(NULL, NULL, ns1__zjqueryObjectOut, ns1__zjqueryObjectOutResponse); }
	virtual	int zjqueryObjectOut(const char *endpoint, const char *soap_action, _ns1__zjqueryObjectOut *ns1__zjqueryObjectOut, _ns1__zjqueryObjectOutResponse &ns1__zjqueryObjectOutResponse);

	/// Web service operation 'GetVer' (returns error code or SOAP_OK)
	virtual	int GetVer_(_ns1__GetVer *ns1__GetVer, _ns1__GetVerResponse &ns1__GetVerResponse) { return this->GetVer_(NULL, NULL, ns1__GetVer, ns1__GetVerResponse); }
	virtual	int GetVer_(const char *endpoint, const char *soap_action, _ns1__GetVer *ns1__GetVer, _ns1__GetVerResponse &ns1__GetVerResponse);

	/// Web service operation 'queryObjectOut' (returns error code or SOAP_OK)
	virtual	int queryObjectOut_(_ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse) { return this->queryObjectOut_(NULL, NULL, ns1__queryObjectOut, ns1__queryObjectOutResponse); }
	virtual	int queryObjectOut_(const char *endpoint, const char *soap_action, _ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse);

	/// Web service operation 'writeObjectOut' (returns error code or SOAP_OK)
	virtual	int writeObjectOut_(_ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse) { return this->writeObjectOut_(NULL, NULL, ns1__writeObjectOut, ns1__writeObjectOutResponse); }
	virtual	int writeObjectOut_(const char *endpoint, const char *soap_action, _ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse);

	/// Web service operation 'NetworkingQueryObjectOut' (returns error code or SOAP_OK)
	virtual	int NetworkingQueryObjectOut_(_ns1__NetworkingQueryObjectOut *ns1__NetworkingQueryObjectOut, _ns1__NetworkingQueryObjectOutResponse &ns1__NetworkingQueryObjectOutResponse) { return this->NetworkingQueryObjectOut_(NULL, NULL, ns1__NetworkingQueryObjectOut, ns1__NetworkingQueryObjectOutResponse); }
	virtual	int NetworkingQueryObjectOut_(const char *endpoint, const char *soap_action, _ns1__NetworkingQueryObjectOut *ns1__NetworkingQueryObjectOut, _ns1__NetworkingQueryObjectOutResponse &ns1__NetworkingQueryObjectOutResponse);

	/// Web service operation 'NetworkingWriteObjectOut' (returns error code or SOAP_OK)
	virtual	int NetworkingWriteObjectOut_(_ns1__NetworkingWriteObjectOut *ns1__NetworkingWriteObjectOut, _ns1__NetworkingWriteObjectOutResponse &ns1__NetworkingWriteObjectOutResponse) { return this->NetworkingWriteObjectOut_(NULL, NULL, ns1__NetworkingWriteObjectOut, ns1__NetworkingWriteObjectOutResponse); }
	virtual	int NetworkingWriteObjectOut_(const char *endpoint, const char *soap_action, _ns1__NetworkingWriteObjectOut *ns1__NetworkingWriteObjectOut, _ns1__NetworkingWriteObjectOutResponse &ns1__NetworkingWriteObjectOutResponse);

	/// Web service operation 'GetLoginParm' (returns error code or SOAP_OK)
	virtual	int GetLoginParm_(_ns1__GetLoginParm *ns1__GetLoginParm, _ns1__GetLoginParmResponse &ns1__GetLoginParmResponse) { return this->GetLoginParm_(NULL, NULL, ns1__GetLoginParm, ns1__GetLoginParmResponse); }
	virtual	int GetLoginParm_(const char *endpoint, const char *soap_action, _ns1__GetLoginParm *ns1__GetLoginParm, _ns1__GetLoginParmResponse &ns1__GetLoginParmResponse);

	/// Web service operation 'zjqueryObjectOut' (returns error code or SOAP_OK)
	virtual	int zjqueryObjectOut_(_ns1__zjqueryObjectOut *ns1__zjqueryObjectOut, _ns1__zjqueryObjectOutResponse &ns1__zjqueryObjectOutResponse) { return this->zjqueryObjectOut_(NULL, NULL, ns1__zjqueryObjectOut, ns1__zjqueryObjectOutResponse); }
	virtual	int zjqueryObjectOut_(const char *endpoint, const char *soap_action, _ns1__zjqueryObjectOut *ns1__zjqueryObjectOut, _ns1__zjqueryObjectOutResponse &ns1__zjqueryObjectOutResponse);
};
#endif
