/* soapTmriOutAccessSoapProxy.h
   Generated by gSOAP 2.8.21 from TmriOutAccess.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapTmriOutAccessSoapProxy_H
#define soapTmriOutAccessSoapProxy_H
#include "soapH.h"

class SOAP_CMAC TmriOutAccessSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'TmriOutAccessSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in TmriOutAccess.h (non-static)
	/// Constructor
	TmriOutAccessSoapProxy();
	/// Construct from another engine state
	TmriOutAccessSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	TmriOutAccessSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	TmriOutAccessSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	TmriOutAccessSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	TmriOutAccessSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~TmriOutAccessSoapProxy();
	/// Initializer used by constructors
	virtual	void TmriOutAccessSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'writeObjectOut' (returns error code or SOAP_OK)
	virtual	int writeObjectOut(_ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse) { return this->writeObjectOut(NULL, NULL, ns1__writeObjectOut, ns1__writeObjectOutResponse); }
	virtual	int writeObjectOut(const char *endpoint, const char *soap_action, _ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse);

	/// Web service operation 'queryObjectOut' (returns error code or SOAP_OK)
	virtual	int queryObjectOut(_ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse) { return this->queryObjectOut(NULL, NULL, ns1__queryObjectOut, ns1__queryObjectOutResponse); }
	virtual	int queryObjectOut(const char *endpoint, const char *soap_action, _ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse);

	/// Web service operation 'URLEncode' (returns error code or SOAP_OK)
	virtual	int URLEncode(_ns1__URLEncode *ns1__URLEncode, _ns1__URLEncodeResponse &ns1__URLEncodeResponse) { return this->URLEncode(NULL, NULL, ns1__URLEncode, ns1__URLEncodeResponse); }
	virtual	int URLEncode(const char *endpoint, const char *soap_action, _ns1__URLEncode *ns1__URLEncode, _ns1__URLEncodeResponse &ns1__URLEncodeResponse);

	/// Web service operation 'URLDecode' (returns error code or SOAP_OK)
	virtual	int URLDecode(_ns1__URLDecode *ns1__URLDecode, _ns1__URLDecodeResponse &ns1__URLDecodeResponse) { return this->URLDecode(NULL, NULL, ns1__URLDecode, ns1__URLDecodeResponse); }
	virtual	int URLDecode(const char *endpoint, const char *soap_action, _ns1__URLDecode *ns1__URLDecode, _ns1__URLDecodeResponse &ns1__URLDecodeResponse);

	/// Web service operation 'writeObjectOut' (returns error code or SOAP_OK)
	virtual	int writeObjectOut_(_ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse) { return this->writeObjectOut_(NULL, NULL, ns1__writeObjectOut, ns1__writeObjectOutResponse); }
	virtual	int writeObjectOut_(const char *endpoint, const char *soap_action, _ns1__writeObjectOut *ns1__writeObjectOut, _ns1__writeObjectOutResponse &ns1__writeObjectOutResponse);

	/// Web service operation 'queryObjectOut' (returns error code or SOAP_OK)
	virtual	int queryObjectOut_(_ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse) { return this->queryObjectOut_(NULL, NULL, ns1__queryObjectOut, ns1__queryObjectOutResponse); }
	virtual	int queryObjectOut_(const char *endpoint, const char *soap_action, _ns1__queryObjectOut *ns1__queryObjectOut, _ns1__queryObjectOutResponse &ns1__queryObjectOutResponse);

	/// Web service operation 'URLEncode' (returns error code or SOAP_OK)
	virtual	int URLEncode_(_ns1__URLEncode *ns1__URLEncode, _ns1__URLEncodeResponse &ns1__URLEncodeResponse) { return this->URLEncode_(NULL, NULL, ns1__URLEncode, ns1__URLEncodeResponse); }
	virtual	int URLEncode_(const char *endpoint, const char *soap_action, _ns1__URLEncode *ns1__URLEncode, _ns1__URLEncodeResponse &ns1__URLEncodeResponse);

	/// Web service operation 'URLDecode' (returns error code or SOAP_OK)
	virtual	int URLDecode_(_ns1__URLDecode *ns1__URLDecode, _ns1__URLDecodeResponse &ns1__URLDecodeResponse) { return this->URLDecode_(NULL, NULL, ns1__URLDecode, ns1__URLDecodeResponse); }
	virtual	int URLDecode_(const char *endpoint, const char *soap_action, _ns1__URLDecode *ns1__URLDecode, _ns1__URLDecodeResponse &ns1__URLDecodeResponse);
};
#endif
