/* soapStub.h
   Generated by gSOAP 2.8.21 from TmriOutAccess.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#define SOAP_NAMESPACE_OF_ns1	"http://localhost:1044/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20821
# error "GSOAP VERSION 20821 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__ns1__writeObjectOut
#define SOAP_TYPE__ns1__writeObjectOut (8)
/* ns1:writeObjectOut */
class SOAP_CMAC _ns1__writeObjectOut
{
public:
	std::wstring *xtlb;	/* optional element of type xsd:string */
	std::wstring *jkxlh;	/* optional element of type xsd:string */
	std::wstring *jkid;	/* optional element of type xsd:string */
	std::wstring *xmlDoc;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique type id SOAP_TYPE__ns1__writeObjectOut */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__writeObjectOut() { _ns1__writeObjectOut::soap_default(NULL); }
	virtual ~_ns1__writeObjectOut() { }
};
#endif

#ifndef SOAP_TYPE__ns1__writeObjectOutResponse
#define SOAP_TYPE__ns1__writeObjectOutResponse (9)
/* ns1:writeObjectOutResponse */
class SOAP_CMAC _ns1__writeObjectOutResponse
{
public:
	std::wstring *writeObjectOutResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique type id SOAP_TYPE__ns1__writeObjectOutResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__writeObjectOutResponse() { _ns1__writeObjectOutResponse::soap_default(NULL); }
	virtual ~_ns1__writeObjectOutResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__queryObjectOut
#define SOAP_TYPE__ns1__queryObjectOut (10)
/* ns1:queryObjectOut */
class SOAP_CMAC _ns1__queryObjectOut
{
public:
	std::wstring *xtlb;	/* optional element of type xsd:string */
	std::wstring *jkxlh;	/* optional element of type xsd:string */
	std::wstring *jkid;	/* optional element of type xsd:string */
	std::wstring *xmlDoc;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique type id SOAP_TYPE__ns1__queryObjectOut */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__queryObjectOut() { _ns1__queryObjectOut::soap_default(NULL); }
	virtual ~_ns1__queryObjectOut() { }
};
#endif

#ifndef SOAP_TYPE__ns1__queryObjectOutResponse
#define SOAP_TYPE__ns1__queryObjectOutResponse (11)
/* ns1:queryObjectOutResponse */
class SOAP_CMAC _ns1__queryObjectOutResponse
{
public:
	std::wstring *queryObjectOutResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique type id SOAP_TYPE__ns1__queryObjectOutResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__queryObjectOutResponse() { _ns1__queryObjectOutResponse::soap_default(NULL); }
	virtual ~_ns1__queryObjectOutResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__URLEncode
#define SOAP_TYPE__ns1__URLEncode (12)
/* ns1:URLEncode */
class SOAP_CMAC _ns1__URLEncode
{
public:
	std::wstring *xtlb;	/* optional element of type xsd:string */
	std::wstring *jkxlh;	/* optional element of type xsd:string */
	std::wstring *data;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique type id SOAP_TYPE__ns1__URLEncode */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__URLEncode() { _ns1__URLEncode::soap_default(NULL); }
	virtual ~_ns1__URLEncode() { }
};
#endif

#ifndef SOAP_TYPE__ns1__URLEncodeResponse
#define SOAP_TYPE__ns1__URLEncodeResponse (13)
/* ns1:URLEncodeResponse */
class SOAP_CMAC _ns1__URLEncodeResponse
{
public:
	std::wstring *URLEncodeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique type id SOAP_TYPE__ns1__URLEncodeResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__URLEncodeResponse() { _ns1__URLEncodeResponse::soap_default(NULL); }
	virtual ~_ns1__URLEncodeResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__URLDecode
#define SOAP_TYPE__ns1__URLDecode (14)
/* ns1:URLDecode */
class SOAP_CMAC _ns1__URLDecode
{
public:
	std::wstring *xtlb;	/* optional element of type xsd:string */
	std::wstring *jkxlh;	/* optional element of type xsd:string */
	std::wstring *data;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 14; } /* = unique type id SOAP_TYPE__ns1__URLDecode */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__URLDecode() { _ns1__URLDecode::soap_default(NULL); }
	virtual ~_ns1__URLDecode() { }
};
#endif

#ifndef SOAP_TYPE__ns1__URLDecodeResponse
#define SOAP_TYPE__ns1__URLDecodeResponse (15)
/* ns1:URLDecodeResponse */
class SOAP_CMAC _ns1__URLDecodeResponse
{
public:
	std::wstring *URLDecodeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique type id SOAP_TYPE__ns1__URLDecodeResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__URLDecodeResponse() { _ns1__URLDecodeResponse::soap_default(NULL); }
	virtual ~_ns1__URLDecodeResponse() { }
};
#endif

#ifndef SOAP_TYPE___ns1__writeObjectOut
#define SOAP_TYPE___ns1__writeObjectOut (22)
/* Operation wrapper: */
struct __ns1__writeObjectOut
{
public:
	_ns1__writeObjectOut *ns1__writeObjectOut;	/* optional element of type ns1:writeObjectOut */
public:
	int soap_type() const { return 22; } /* = unique type id SOAP_TYPE___ns1__writeObjectOut */
};
#endif

#ifndef SOAP_TYPE___ns1__queryObjectOut
#define SOAP_TYPE___ns1__queryObjectOut (26)
/* Operation wrapper: */
struct __ns1__queryObjectOut
{
public:
	_ns1__queryObjectOut *ns1__queryObjectOut;	/* optional element of type ns1:queryObjectOut */
public:
	int soap_type() const { return 26; } /* = unique type id SOAP_TYPE___ns1__queryObjectOut */
};
#endif

#ifndef SOAP_TYPE___ns1__URLEncode
#define SOAP_TYPE___ns1__URLEncode (30)
/* Operation wrapper: */
struct __ns1__URLEncode
{
public:
	_ns1__URLEncode *ns1__URLEncode;	/* optional element of type ns1:URLEncode */
public:
	int soap_type() const { return 30; } /* = unique type id SOAP_TYPE___ns1__URLEncode */
};
#endif

#ifndef SOAP_TYPE___ns1__URLDecode
#define SOAP_TYPE___ns1__URLDecode (34)
/* Operation wrapper: */
struct __ns1__URLDecode
{
public:
	_ns1__URLDecode *ns1__URLDecode;	/* optional element of type ns1:URLDecode */
public:
	int soap_type() const { return 34; } /* = unique type id SOAP_TYPE___ns1__URLDecode */
};
#endif

#ifndef SOAP_TYPE___ns1__writeObjectOut_
#define SOAP_TYPE___ns1__writeObjectOut_ (36)
/* Operation wrapper: */
struct __ns1__writeObjectOut_
{
public:
	_ns1__writeObjectOut *ns1__writeObjectOut;	/* optional element of type ns1:writeObjectOut */
public:
	int soap_type() const { return 36; } /* = unique type id SOAP_TYPE___ns1__writeObjectOut_ */
};
#endif

#ifndef SOAP_TYPE___ns1__queryObjectOut_
#define SOAP_TYPE___ns1__queryObjectOut_ (38)
/* Operation wrapper: */
struct __ns1__queryObjectOut_
{
public:
	_ns1__queryObjectOut *ns1__queryObjectOut;	/* optional element of type ns1:queryObjectOut */
public:
	int soap_type() const { return 38; } /* = unique type id SOAP_TYPE___ns1__queryObjectOut_ */
};
#endif

#ifndef SOAP_TYPE___ns1__URLEncode_
#define SOAP_TYPE___ns1__URLEncode_ (40)
/* Operation wrapper: */
struct __ns1__URLEncode_
{
public:
	_ns1__URLEncode *ns1__URLEncode;	/* optional element of type ns1:URLEncode */
public:
	int soap_type() const { return 40; } /* = unique type id SOAP_TYPE___ns1__URLEncode_ */
};
#endif

#ifndef SOAP_TYPE___ns1__URLDecode_
#define SOAP_TYPE___ns1__URLDecode_ (42)
/* Operation wrapper: */
struct __ns1__URLDecode_
{
public:
	_ns1__URLDecode *ns1__URLDecode;	/* optional element of type ns1:URLDecode */
public:
	int soap_type() const { return 42; } /* = unique type id SOAP_TYPE___ns1__URLDecode_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (43)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 43; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (44)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 44; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (46)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 46; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (49)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 49; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (50)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 50; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
