/*
* Copyright (c) 佛山市南华仪器股份有限公司
* All rights reserved.
*
* 文件名称：OtherData.h
* 文件标识：
* 描述：其它数据表模型
*
* 版本：1.0
* 日期：20xx-xx-xx
* 作者：Cyx
*
*
* 历史信息：
*
* 版本：1.0.0beta1
* 日期：20xx-xx-xx
* 作者：Cyx
* 描述：正在开发
*/

#if !defined (NHMFDSERVERDBMODEL_OTHERDATA_H)
#define NHMFDSERVERDBMODEL_OTHERDATA_H

#include <string>

struct SOtherData
{
	// 自动编号
	std::wstring strAutoID;
	// 日志编号(年月日时分秒IP)
	std::wstring strRunningNumber;
	// 数据1
	std::wstring strData1;
	// 数据2
	std::wstring strData2;
	// 数据3
	std::wstring strData3;
	// 数据4
	std::wstring strData4;
	// 数据5
	std::wstring strData5;
	// 数据6
	std::wstring strData6;
	// 数据7
	std::wstring strData7;
	// 数据8
	std::wstring strData8;
	// 数据9
	std::wstring strData9;
	// 数据10
	std::wstring strData10;
	// 数据11
	std::wstring strData11;
	// 数据12
	std::wstring strData12;
	// 数据13
	std::wstring strData13;
	// 数据14
	std::wstring strData14;
	// 数据15
	std::wstring strData15;
	// 数据16
	std::wstring strData16;
	// 数据17
	std::wstring strData17;
	// 数据18
	std::wstring strData18;
	// 数据19
	std::wstring strData19;
	// 数据20
	std::wstring strData20;
	// 数据21
	std::wstring strData21;
	// 数据22
	std::wstring strData22;
	// 数据23
	std::wstring strData23;
	// 数据24
	std::wstring strData24;
	// 数据25
	std::wstring strData25;
	// 数据26
	std::wstring strData26;
	// 数据27
	std::wstring strData27;
	// 数据28
	std::wstring strData28;
	// 数据29
	std::wstring strData29;
	// 数据30
	std::wstring strData30;
	// 数据31
	std::wstring strData31;
	// 数据32
	std::wstring strData32;
	// 数据33
	std::wstring strData33;
	// 数据34
	std::wstring strData34;
	// 数据35
	std::wstring strData35;
	// 数据36
	std::wstring strData36;
	// 数据37
	std::wstring strData37;
	// 数据38
	std::wstring strData38;
	// 数据39
	std::wstring strData39;
	// 数据40
	std::wstring strData40;
	// 数据41
	std::wstring strData41;
	// 数据42
	std::wstring strData42;
	// 数据43
	std::wstring strData43;
	// 数据44
	std::wstring strData44;
	// 数据45
	std::wstring strData45;
	// 数据46
	std::wstring strData46;
	// 数据47
	std::wstring strData47;
	// 数据48
	std::wstring strData48;
	// 数据49
	std::wstring strData49;
	// 数据50
	std::wstring strData50;
	// 数据51
	std::wstring strData51;
	// 数据52
	std::wstring strData52;
	// 数据53
	std::wstring strData53;
	// 数据54
	std::wstring strData54;
	// 数据55
	std::wstring strData55;
	// 数据56
	std::wstring strData56;
	// 数据57
	std::wstring strData57;
	// 数据58
	std::wstring strData58;
	// 数据59
	std::wstring strData59;
	// 数据60
	std::wstring strData60;
	// 二进制数据1
	std::string strBinaryData1;
	// 二进制数据2
	std::string strBinaryData2;
	// 二进制数据3
	std::string strBinaryData3;
	// 二进制数据4
	std::string strBinaryData4;
	// 二进制数据5
	std::string strBinaryData5;
	// 二进制数据6
	std::string strBinaryData6;
	// 二进制数据7
	std::string strBinaryData7;
	// 二进制数据8
	std::string strBinaryData8;
	// 二进制数据9
	std::string strBinaryData9;
	// 二进制数据10
	std::string strBinaryData10;
	// 备注
	std::wstring strRemark;
	// 保留1
	std::wstring strReserved1;
	// 保留2
	std::wstring strReserved2;
	// 保留3
	std::wstring strReserved3;
};
#endif