#if !defined (NHMFDSERVERDBMODEL_RATING_H)
#define NHMFDSERVERDBMODEL_RATING_H

#include <string>

struct SRating
{
	// 自动编号
	std::wstring strAutoID;
	// 日志编号(年月日时分秒IP)
	std::wstring strRunningNumber;
	// 评定人
	std::wstring strRater;
	// 技术等级（1-一级，2-二级，3-三级，4-合格，5-不合格）
	std::wstring strTecRat;
	// 项目1
	std::wstring strItem1;
	// 项目2		  
	std::wstring strItem2;
	// 项目3		  
	std::wstring strItem3;
	// 项目4		  
	std::wstring strItem4;
	// 项目5		  
	std::wstring strItem5;
	// 项目6		  
	std::wstring strItem6;
	// 项目7		  
	std::wstring strItem7;
	// 项目8		  
	std::wstring strItem8;
	// 项目9		  
	std::wstring strItem9;
	// 项目10		 
	std::wstring strItem10;
	// 项目11		  
	std::wstring strItem11;
	// 项目12		  
	std::wstring strItem12;
	// 项目13		  
	std::wstring strItem13;
	// 项目14		  
	std::wstring strItem14;
	// 项目15		  
	std::wstring strItem15;
	// 项目16		 
	std::wstring strItem16;
	// 项目17		  
	std::wstring strItem17;
	// 项目18		 
	std::wstring strItem18;
	// 项目19		  
	std::wstring strItem19;
	// 项目20		 
	std::wstring strItem20;
	// 项目21		  
	std::wstring strItem21;
	// 项目22		  
	std::wstring strItem22;
	// 项目23		 
	std::wstring strItem23;
	// 项目24		
	std::wstring strItem24;
	// 项目25		 
	std::wstring strItem25;
	// 项目26		  
	std::wstring strItem26;
	// 项目27		  
	std::wstring strItem27;
	// 项目28		 
	std::wstring strItem28;
	// 项目29		  
	std::wstring strItem29;
	// 项目30		 
	std::wstring strItem30;
	// 项目31		  
	std::wstring strItem31;
	// 项目32		  
	std::wstring strItem32;
	// 项目33		  
	std::wstring strItem33;
	// 项目34		  
	std::wstring strItem34;
	// 项目35		  
	std::wstring strItem35;
	// 项目36		 
	std::wstring strItem36;
	// 项目37		  
	std::wstring strItem37;
	// 项目38		 
	std::wstring strItem38;
	// 项目39		  
	std::wstring strItem39;
	// 项目40		 
	std::wstring strItem40;
	// 项目41		  
	std::wstring strItem41;
	// 项目42		  
	std::wstring strItem42;
	// 项目43		 
	std::wstring strItem43;
	// 项目44		
	std::wstring strItem44;
	// 项目45		 
	std::wstring strItem45;
	// 项目46		  
	std::wstring strItem46;
	// 项目47		  
	std::wstring strItem47;
	// 项目48		 
	std::wstring strItem48;
	// 项目49		  
	std::wstring strItem49;
	// 项目50		 
	std::wstring strItem50;
	// 项目51		  
	std::wstring strItem51;
	// 项目52		  
	std::wstring strItem52;
	// 项目53		 
	std::wstring strItem53;
	// 项目54		
	std::wstring strItem54;
	// 项目55		 
	std::wstring strItem55;
	// 项目56		  
	std::wstring strItem56;
	// 项目57		  
	std::wstring strItem57;
	// 项目58		 
	std::wstring strItem58;
	// 项目59		  
	std::wstring strItem59;
	// 项目60		 
	std::wstring strItem60;
	
	// 备注
	std::wstring strRemark;
	// 保留1
	std::wstring strReserved1;
	// 保留2
	std::wstring strReserved2;
	// 保留3
	std::wstring strReserved3;
};
#endif