/* soapH.h
   Generated by gSOAP 2.7.17 from WebService.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_std__wstring
#define SOAP_TYPE_std__wstring (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__wstring(struct soap*, std::wstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__wstring(struct soap*, const std::wstring *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__wstring(struct soap*, const char*, int, const std::wstring*, const char*);
SOAP_FMAC3 std::wstring * SOAP_FMAC4 soap_in_std__wstring(struct soap*, const char*, std::wstring*, const char*);

#define soap_write_std__wstring(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__wstring(struct soap*, const std::wstring *, const char*, const char*);

#define soap_read_std__wstring(soap, data) ( soap_begin_recv(soap) || !soap_get_std__wstring(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::wstring * SOAP_FMAC4 soap_get_std__wstring(struct soap*, std::wstring *, const char*, const char*);

#define soap_new_std__wstring(soap, n) soap_instantiate_std__wstring(soap, n, NULL, NULL, NULL)


#define soap_delete_std__wstring(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::wstring * SOAP_FMAC2 soap_instantiate_std__wstring(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__wstring(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_WS1__writeObjectOut_
#define SOAP_TYPE_WS1__writeObjectOut_ (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__writeObjectOut_(struct soap*, struct WS1__writeObjectOut_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__writeObjectOut_(struct soap*, const struct WS1__writeObjectOut_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__writeObjectOut_(struct soap*, const char*, int, const struct WS1__writeObjectOut_ *, const char*);
SOAP_FMAC3 struct WS1__writeObjectOut_ * SOAP_FMAC4 soap_in_WS1__writeObjectOut_(struct soap*, const char*, struct WS1__writeObjectOut_ *, const char*);

#define soap_write_WS1__writeObjectOut_(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__writeObjectOut_(soap, data), 0) || soap_put_WS1__writeObjectOut_(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__writeObjectOut_(struct soap*, const struct WS1__writeObjectOut_ *, const char*, const char*);

#define soap_read_WS1__writeObjectOut_(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__writeObjectOut_(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__writeObjectOut_ * SOAP_FMAC4 soap_get_WS1__writeObjectOut_(struct soap*, struct WS1__writeObjectOut_ *, const char*, const char*);

#define soap_new_WS1__writeObjectOut_(soap, n) soap_instantiate_WS1__writeObjectOut_(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__writeObjectOut_(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__writeObjectOut_ * SOAP_FMAC2 soap_instantiate_WS1__writeObjectOut_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__writeObjectOut_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS1__writeObjectOut_Response
#define SOAP_TYPE_WS1__writeObjectOut_Response (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__writeObjectOut_Response(struct soap*, struct WS1__writeObjectOut_Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__writeObjectOut_Response(struct soap*, const struct WS1__writeObjectOut_Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__writeObjectOut_Response(struct soap*, const char*, int, const struct WS1__writeObjectOut_Response *, const char*);
SOAP_FMAC3 struct WS1__writeObjectOut_Response * SOAP_FMAC4 soap_in_WS1__writeObjectOut_Response(struct soap*, const char*, struct WS1__writeObjectOut_Response *, const char*);

#define soap_write_WS1__writeObjectOut_Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__writeObjectOut_Response(soap, data), 0) || soap_put_WS1__writeObjectOut_Response(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__writeObjectOut_Response(struct soap*, const struct WS1__writeObjectOut_Response *, const char*, const char*);

#define soap_read_WS1__writeObjectOut_Response(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__writeObjectOut_Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__writeObjectOut_Response * SOAP_FMAC4 soap_get_WS1__writeObjectOut_Response(struct soap*, struct WS1__writeObjectOut_Response *, const char*, const char*);

#define soap_new_WS1__writeObjectOut_Response(soap, n) soap_instantiate_WS1__writeObjectOut_Response(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__writeObjectOut_Response(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__writeObjectOut_Response * SOAP_FMAC2 soap_instantiate_WS1__writeObjectOut_Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__writeObjectOut_Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS1__writeObjectOut
#define SOAP_TYPE_WS1__writeObjectOut (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__writeObjectOut(struct soap*, struct WS1__writeObjectOut *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__writeObjectOut(struct soap*, const struct WS1__writeObjectOut *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__writeObjectOut(struct soap*, const char*, int, const struct WS1__writeObjectOut *, const char*);
SOAP_FMAC3 struct WS1__writeObjectOut * SOAP_FMAC4 soap_in_WS1__writeObjectOut(struct soap*, const char*, struct WS1__writeObjectOut *, const char*);

#define soap_write_WS1__writeObjectOut(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__writeObjectOut(soap, data), 0) || soap_put_WS1__writeObjectOut(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__writeObjectOut(struct soap*, const struct WS1__writeObjectOut *, const char*, const char*);

#define soap_read_WS1__writeObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__writeObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__writeObjectOut * SOAP_FMAC4 soap_get_WS1__writeObjectOut(struct soap*, struct WS1__writeObjectOut *, const char*, const char*);

#define soap_new_WS1__writeObjectOut(soap, n) soap_instantiate_WS1__writeObjectOut(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__writeObjectOut(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__writeObjectOut * SOAP_FMAC2 soap_instantiate_WS1__writeObjectOut(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__writeObjectOut(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS1__writeObjectOutResponse
#define SOAP_TYPE_WS1__writeObjectOutResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__writeObjectOutResponse(struct soap*, struct WS1__writeObjectOutResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__writeObjectOutResponse(struct soap*, const struct WS1__writeObjectOutResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__writeObjectOutResponse(struct soap*, const char*, int, const struct WS1__writeObjectOutResponse *, const char*);
SOAP_FMAC3 struct WS1__writeObjectOutResponse * SOAP_FMAC4 soap_in_WS1__writeObjectOutResponse(struct soap*, const char*, struct WS1__writeObjectOutResponse *, const char*);

#define soap_write_WS1__writeObjectOutResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__writeObjectOutResponse(soap, data), 0) || soap_put_WS1__writeObjectOutResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__writeObjectOutResponse(struct soap*, const struct WS1__writeObjectOutResponse *, const char*, const char*);

#define soap_read_WS1__writeObjectOutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__writeObjectOutResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__writeObjectOutResponse * SOAP_FMAC4 soap_get_WS1__writeObjectOutResponse(struct soap*, struct WS1__writeObjectOutResponse *, const char*, const char*);

#define soap_new_WS1__writeObjectOutResponse(soap, n) soap_instantiate_WS1__writeObjectOutResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__writeObjectOutResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__writeObjectOutResponse * SOAP_FMAC2 soap_instantiate_WS1__writeObjectOutResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__writeObjectOutResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS1__queryObjectOut_
#define SOAP_TYPE_WS1__queryObjectOut_ (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__queryObjectOut_(struct soap*, struct WS1__queryObjectOut_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__queryObjectOut_(struct soap*, const struct WS1__queryObjectOut_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__queryObjectOut_(struct soap*, const char*, int, const struct WS1__queryObjectOut_ *, const char*);
SOAP_FMAC3 struct WS1__queryObjectOut_ * SOAP_FMAC4 soap_in_WS1__queryObjectOut_(struct soap*, const char*, struct WS1__queryObjectOut_ *, const char*);

#define soap_write_WS1__queryObjectOut_(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__queryObjectOut_(soap, data), 0) || soap_put_WS1__queryObjectOut_(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__queryObjectOut_(struct soap*, const struct WS1__queryObjectOut_ *, const char*, const char*);

#define soap_read_WS1__queryObjectOut_(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__queryObjectOut_(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__queryObjectOut_ * SOAP_FMAC4 soap_get_WS1__queryObjectOut_(struct soap*, struct WS1__queryObjectOut_ *, const char*, const char*);

#define soap_new_WS1__queryObjectOut_(soap, n) soap_instantiate_WS1__queryObjectOut_(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__queryObjectOut_(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__queryObjectOut_ * SOAP_FMAC2 soap_instantiate_WS1__queryObjectOut_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__queryObjectOut_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS1__queryObjectOut_Response
#define SOAP_TYPE_WS1__queryObjectOut_Response (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__queryObjectOut_Response(struct soap*, struct WS1__queryObjectOut_Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__queryObjectOut_Response(struct soap*, const struct WS1__queryObjectOut_Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__queryObjectOut_Response(struct soap*, const char*, int, const struct WS1__queryObjectOut_Response *, const char*);
SOAP_FMAC3 struct WS1__queryObjectOut_Response * SOAP_FMAC4 soap_in_WS1__queryObjectOut_Response(struct soap*, const char*, struct WS1__queryObjectOut_Response *, const char*);

#define soap_write_WS1__queryObjectOut_Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__queryObjectOut_Response(soap, data), 0) || soap_put_WS1__queryObjectOut_Response(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__queryObjectOut_Response(struct soap*, const struct WS1__queryObjectOut_Response *, const char*, const char*);

#define soap_read_WS1__queryObjectOut_Response(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__queryObjectOut_Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__queryObjectOut_Response * SOAP_FMAC4 soap_get_WS1__queryObjectOut_Response(struct soap*, struct WS1__queryObjectOut_Response *, const char*, const char*);

#define soap_new_WS1__queryObjectOut_Response(soap, n) soap_instantiate_WS1__queryObjectOut_Response(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__queryObjectOut_Response(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__queryObjectOut_Response * SOAP_FMAC2 soap_instantiate_WS1__queryObjectOut_Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__queryObjectOut_Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS1__queryObjectOut
#define SOAP_TYPE_WS1__queryObjectOut (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__queryObjectOut(struct soap*, struct WS1__queryObjectOut *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__queryObjectOut(struct soap*, const struct WS1__queryObjectOut *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__queryObjectOut(struct soap*, const char*, int, const struct WS1__queryObjectOut *, const char*);
SOAP_FMAC3 struct WS1__queryObjectOut * SOAP_FMAC4 soap_in_WS1__queryObjectOut(struct soap*, const char*, struct WS1__queryObjectOut *, const char*);

#define soap_write_WS1__queryObjectOut(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__queryObjectOut(soap, data), 0) || soap_put_WS1__queryObjectOut(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__queryObjectOut(struct soap*, const struct WS1__queryObjectOut *, const char*, const char*);

#define soap_read_WS1__queryObjectOut(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__queryObjectOut(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__queryObjectOut * SOAP_FMAC4 soap_get_WS1__queryObjectOut(struct soap*, struct WS1__queryObjectOut *, const char*, const char*);

#define soap_new_WS1__queryObjectOut(soap, n) soap_instantiate_WS1__queryObjectOut(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__queryObjectOut(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__queryObjectOut * SOAP_FMAC2 soap_instantiate_WS1__queryObjectOut(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__queryObjectOut(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS1__queryObjectOutResponse
#define SOAP_TYPE_WS1__queryObjectOutResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WS1__queryObjectOutResponse(struct soap*, struct WS1__queryObjectOutResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WS1__queryObjectOutResponse(struct soap*, const struct WS1__queryObjectOutResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WS1__queryObjectOutResponse(struct soap*, const char*, int, const struct WS1__queryObjectOutResponse *, const char*);
SOAP_FMAC3 struct WS1__queryObjectOutResponse * SOAP_FMAC4 soap_in_WS1__queryObjectOutResponse(struct soap*, const char*, struct WS1__queryObjectOutResponse *, const char*);

#define soap_write_WS1__queryObjectOutResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_WS1__queryObjectOutResponse(soap, data), 0) || soap_put_WS1__queryObjectOutResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WS1__queryObjectOutResponse(struct soap*, const struct WS1__queryObjectOutResponse *, const char*, const char*);

#define soap_read_WS1__queryObjectOutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_WS1__queryObjectOutResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct WS1__queryObjectOutResponse * SOAP_FMAC4 soap_get_WS1__queryObjectOutResponse(struct soap*, struct WS1__queryObjectOutResponse *, const char*, const char*);

#define soap_new_WS1__queryObjectOutResponse(soap, n) soap_instantiate_WS1__queryObjectOutResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_WS1__queryObjectOutResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct WS1__queryObjectOutResponse * SOAP_FMAC2 soap_instantiate_WS1__queryObjectOutResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WS1__queryObjectOutResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
