/* soapStub.h
   Generated by gSOAP 2.8.108 for jcjkService.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <vector>
#define SOAP_NAMESPACE_OF_ns1	"http://192.168.70.254:9380/jcjklw/services/jcjkService"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208108
# error "GSOAP VERSION 208108 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

class SOAP_ENC__Array;	/* jcjkService.h:151 */
class SOAP_ENC__base64Binary;	/* jcjkService.h:160 */
class ArrayOf_USCOREsoapenc_USCOREstring;	/* jcjkService.h:174 */
struct ns2__mainResponse;	/* jcjkService.h:313 */
struct ns2__main;	/* jcjkService.h:373 */
struct ns2__initResponse;	/* jcjkService.h:384 */
struct ns2__init;	/* jcjkService.h:441 */
struct ns2__checkNullResponse;	/* jcjkService.h:452 */
struct ns2__checkNull;	/* jcjkService.h:516 */
struct ns2__writeObjectOutResponse;	/* jcjkService.h:592 */
struct ns2__writeObjectOut;	/* jcjkService.h:592 */
struct ns2__uploadFileResponse;	/* jcjkService.h:671 */
struct ns2__uploadFile;	/* jcjkService.h:671 */
struct ns2__getZpgwcsResponse;	/* jcjkService.h:744 */
struct ns2__getZpgwcs;	/* jcjkService.h:744 */
struct ns2__uploadWjzpResponse;	/* jcjkService.h:811 */
struct ns2__uploadWjzp;	/* jcjkService.h:811 */
struct ns2__queryObjectOutResponse;	/* jcjkService.h:887 */
struct ns2__queryObjectOut;	/* jcjkService.h:887 */

/* jcjkService.h:151 */
#ifndef SOAP_TYPE_SOAP_ENC__Array
#define SOAP_TYPE_SOAP_ENC__Array (8)
/* Sequence of SOAP-ENC:Array schema type: */
class SOAP_CMAC SOAP_ENC__Array {
      public:
        char **__ptr;
        int __size;
      public:
        /// Return unique type id SOAP_TYPE_SOAP_ENC__Array
        virtual long soap_type(void) const { return SOAP_TYPE_SOAP_ENC__Array; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type SOAP_ENC__Array, default initialized and not managed by a soap context
        virtual SOAP_ENC__Array *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(SOAP_ENC__Array); }
      public:
        /// Constructor with default initializations
        SOAP_ENC__Array() : __ptr(), __size() { }
        virtual ~SOAP_ENC__Array() { }
        /// Friend allocator used by soap_new_SOAP_ENC__Array(struct soap*, int)
        friend SOAP_FMAC1 SOAP_ENC__Array * SOAP_FMAC2 soap_instantiate_SOAP_ENC__Array(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:160 */
#ifndef SOAP_TYPE_SOAP_ENC__base64Binary
#define SOAP_TYPE_SOAP_ENC__base64Binary (10)
/* base64Binary XML schema type: */
class SOAP_CMAC SOAP_ENC__base64Binary {
      public:
        unsigned char *__ptr;
        int __size;
      public:
        /// Return unique type id SOAP_TYPE_SOAP_ENC__base64Binary
        virtual long soap_type(void) const { return SOAP_TYPE_SOAP_ENC__base64Binary; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type SOAP_ENC__base64Binary, default initialized and not managed by a soap context
        virtual SOAP_ENC__base64Binary *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(SOAP_ENC__base64Binary); }
      public:
        /// Constructor with default initializations
        SOAP_ENC__base64Binary() : __ptr(), __size() { }
        virtual ~SOAP_ENC__base64Binary() { }
        /// Friend allocator used by soap_new_SOAP_ENC__base64Binary(struct soap*, int)
        friend SOAP_FMAC1 SOAP_ENC__base64Binary * SOAP_FMAC2 soap_instantiate_SOAP_ENC__base64Binary(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:174 */
#ifndef SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring
#define SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring (14)
/* SOAP encoded array of xsd:string schema type: */
class SOAP_CMAC ArrayOf_USCOREsoapenc_USCOREstring {
      public:
        std::wstring *__ptr;
        int __size;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring
        virtual long soap_type(void) const { return SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ArrayOf_USCOREsoapenc_USCOREstring, default initialized and not managed by a soap context
        virtual ArrayOf_USCOREsoapenc_USCOREstring *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(ArrayOf_USCOREsoapenc_USCOREstring); }
      public:
        /// Constructor with default initializations
        ArrayOf_USCOREsoapenc_USCOREstring() : __ptr(), __size(), soap() { }
        virtual ~ArrayOf_USCOREsoapenc_USCOREstring() { }
        /// Friend allocator used by soap_new_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, int)
        friend SOAP_FMAC1 ArrayOf_USCOREsoapenc_USCOREstring * SOAP_FMAC2 soap_instantiate_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:313 */
#ifndef SOAP_TYPE_ns2__mainResponse
#define SOAP_TYPE_ns2__mainResponse (18)
/* complex XML schema type 'ns2:mainResponse': */
struct SOAP_CMAC ns2__mainResponse {
      public:
        /** Return unique type id SOAP_TYPE_ns2__mainResponse */
        long soap_type() const { return SOAP_TYPE_ns2__mainResponse; }
        /** Constructor with member initializations */
        ns2__mainResponse() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__mainResponse * SOAP_FMAC2 soap_instantiate_ns2__mainResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:373 */
#ifndef SOAP_TYPE_ns2__main
#define SOAP_TYPE_ns2__main (22)
/* complex XML schema type 'ns2:main': */
struct SOAP_CMAC ns2__main {
      public:
        /** Optional element 'args' of XML schema type 'ArrayOfstring' */
        ArrayOf_USCOREsoapenc_USCOREstring *_args;
      public:
        /** Return unique type id SOAP_TYPE_ns2__main */
        long soap_type() const { return SOAP_TYPE_ns2__main; }
        /** Constructor with member initializations */
        ns2__main() : _args() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__main * SOAP_FMAC2 soap_instantiate_ns2__main(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:384 */
#ifndef SOAP_TYPE_ns2__initResponse
#define SOAP_TYPE_ns2__initResponse (23)
/* complex XML schema type 'ns2:initResponse': */
struct SOAP_CMAC ns2__initResponse {
      public:
        /** Return unique type id SOAP_TYPE_ns2__initResponse */
        long soap_type() const { return SOAP_TYPE_ns2__initResponse; }
        /** Constructor with member initializations */
        ns2__initResponse() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__initResponse * SOAP_FMAC2 soap_instantiate_ns2__initResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:441 */
#ifndef SOAP_TYPE_ns2__init
#define SOAP_TYPE_ns2__init (26)
/* complex XML schema type 'ns2:init': */
struct SOAP_CMAC ns2__init {
      public:
        /** Return unique type id SOAP_TYPE_ns2__init */
        long soap_type() const { return SOAP_TYPE_ns2__init; }
        /** Constructor with member initializations */
        ns2__init() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__init * SOAP_FMAC2 soap_instantiate_ns2__init(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:452 */
#ifndef SOAP_TYPE_ns2__checkNullResponse
#define SOAP_TYPE_ns2__checkNullResponse (27)
/* complex XML schema type 'ns2:checkNullResponse': */
struct SOAP_CMAC ns2__checkNullResponse {
      public:
        /** Optional element 'checkNullReturn' of XML schema type 'ArrayOfstring' */
        ArrayOf_USCOREsoapenc_USCOREstring *_checkNullReturn;
      public:
        /** Return unique type id SOAP_TYPE_ns2__checkNullResponse */
        long soap_type() const { return SOAP_TYPE_ns2__checkNullResponse; }
        /** Constructor with member initializations */
        ns2__checkNullResponse() : _checkNullReturn() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__checkNullResponse * SOAP_FMAC2 soap_instantiate_ns2__checkNullResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:516 */
#ifndef SOAP_TYPE_ns2__checkNull
#define SOAP_TYPE_ns2__checkNull (30)
/* complex XML schema type 'ns2:checkNull': */
struct SOAP_CMAC ns2__checkNull {
      public:
        /** Optional element 'params' of XML schema type 'ArrayOfstring' */
        ArrayOf_USCOREsoapenc_USCOREstring *_params;
        /** Optional element 'paramNames' of XML schema type 'ArrayOfstring' */
        ArrayOf_USCOREsoapenc_USCOREstring *_paramNames;
      public:
        /** Return unique type id SOAP_TYPE_ns2__checkNull */
        long soap_type() const { return SOAP_TYPE_ns2__checkNull; }
        /** Constructor with member initializations */
        ns2__checkNull() : _params(), _paramNames() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__checkNull * SOAP_FMAC2 soap_instantiate_ns2__checkNull(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:592 */
#ifndef SOAP_TYPE_ns2__writeObjectOutResponse
#define SOAP_TYPE_ns2__writeObjectOutResponse (33)
/* complex XML schema type 'ns2:writeObjectOutResponse': */
struct SOAP_CMAC ns2__writeObjectOutResponse {
      public:
        /** Required element 'writeObjectOutReturn' of XML schema type 'xsd:string' */
        std::wstring _writeObjectOutReturn;
      public:
        /** Return unique type id SOAP_TYPE_ns2__writeObjectOutResponse */
        long soap_type() const { return SOAP_TYPE_ns2__writeObjectOutResponse; }
        /** Constructor with member initializations */
        ns2__writeObjectOutResponse() : _writeObjectOutReturn() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__writeObjectOutResponse * SOAP_FMAC2 soap_instantiate_ns2__writeObjectOutResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:592 */
#ifndef SOAP_TYPE_ns2__writeObjectOut
#define SOAP_TYPE_ns2__writeObjectOut (34)
/* complex XML schema type 'ns2:writeObjectOut': */
struct SOAP_CMAC ns2__writeObjectOut {
      public:
        /** Required element 'xtlb' of XML schema type 'xsd:string' */
        std::wstring _xtlb;
        /** Required element 'jkxlh' of XML schema type 'xsd:string' */
        std::wstring _jkxlh;
        /** Required element 'jkid' of XML schema type 'xsd:string' */
        std::wstring _jkid;
        /** Required element 'WriteXmlDoc' of XML schema type 'xsd:string' */
        std::wstring _WriteXmlDoc;
      public:
        /** Return unique type id SOAP_TYPE_ns2__writeObjectOut */
        long soap_type() const { return SOAP_TYPE_ns2__writeObjectOut; }
        /** Constructor with member initializations */
        ns2__writeObjectOut() : _xtlb(), _jkxlh(), _jkid(), _WriteXmlDoc() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__writeObjectOut * SOAP_FMAC2 soap_instantiate_ns2__writeObjectOut(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:671 */
#ifndef SOAP_TYPE_ns2__uploadFileResponse
#define SOAP_TYPE_ns2__uploadFileResponse (36)
/* complex XML schema type 'ns2:uploadFileResponse': */
struct SOAP_CMAC ns2__uploadFileResponse {
      public:
        /** Required element 'uploadFileReturn' of XML schema type 'xsd:string' */
        std::wstring _uploadFileReturn;
      public:
        /** Return unique type id SOAP_TYPE_ns2__uploadFileResponse */
        long soap_type() const { return SOAP_TYPE_ns2__uploadFileResponse; }
        /** Constructor with member initializations */
        ns2__uploadFileResponse() : _uploadFileReturn() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__uploadFileResponse * SOAP_FMAC2 soap_instantiate_ns2__uploadFileResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:671 */
#ifndef SOAP_TYPE_ns2__uploadFile
#define SOAP_TYPE_ns2__uploadFile (37)
/* complex XML schema type 'ns2:uploadFile': */
struct SOAP_CMAC ns2__uploadFile {
      public:
        /** Required element 'xtlb' of XML schema type 'xsd:string' */
        std::wstring _xtlb;
        /** Required element 'jkxlh' of XML schema type 'xsd:string' */
        std::wstring _jkxlh;
        /** Required element 'jkid' of XML schema type 'xsd:string' */
        std::wstring _jkid;
        /** Required element 'fileNode' of XML schema type 'SOAP-ENC:base64Binary' */
        SOAP_ENC__base64Binary _fileNode;
        /** Required element 'WriteXmlDoc' of XML schema type 'xsd:string' */
        std::wstring _WriteXmlDoc;
      public:
        /** Return unique type id SOAP_TYPE_ns2__uploadFile */
        long soap_type() const { return SOAP_TYPE_ns2__uploadFile; }
        /** Constructor with member initializations */
        ns2__uploadFile() : _xtlb(), _jkxlh(), _jkid(), _fileNode(), _WriteXmlDoc() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__uploadFile * SOAP_FMAC2 soap_instantiate_ns2__uploadFile(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:744 */
#ifndef SOAP_TYPE_ns2__getZpgwcsResponse
#define SOAP_TYPE_ns2__getZpgwcsResponse (39)
/* complex XML schema type 'ns2:getZpgwcsResponse': */
struct SOAP_CMAC ns2__getZpgwcsResponse {
      public:
        /** Required element 'getZpgwcsReturn' of XML schema type 'xsd:string' */
        std::wstring _getZpgwcsReturn;
      public:
        /** Return unique type id SOAP_TYPE_ns2__getZpgwcsResponse */
        long soap_type() const { return SOAP_TYPE_ns2__getZpgwcsResponse; }
        /** Constructor with member initializations */
        ns2__getZpgwcsResponse() : _getZpgwcsReturn() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__getZpgwcsResponse * SOAP_FMAC2 soap_instantiate_ns2__getZpgwcsResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:744 */
#ifndef SOAP_TYPE_ns2__getZpgwcs
#define SOAP_TYPE_ns2__getZpgwcs (40)
/* complex XML schema type 'ns2:getZpgwcs': */
struct SOAP_CMAC ns2__getZpgwcs {
      public:
        /** Required element 'jcz' of XML schema type 'xsd:string' */
        std::wstring _jcz;
        /** Required element 'jcxdm' of XML schema type 'xsd:string' */
        std::wstring _jcxdm;
        /** Required element 'jcxm' of XML schema type 'xsd:string' */
        std::wstring _jcxm;
      public:
        /** Return unique type id SOAP_TYPE_ns2__getZpgwcs */
        long soap_type() const { return SOAP_TYPE_ns2__getZpgwcs; }
        /** Constructor with member initializations */
        ns2__getZpgwcs() : _jcz(), _jcxdm(), _jcxm() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__getZpgwcs * SOAP_FMAC2 soap_instantiate_ns2__getZpgwcs(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:811 */
#ifndef SOAP_TYPE_ns2__uploadWjzpResponse
#define SOAP_TYPE_ns2__uploadWjzpResponse (42)
/* complex XML schema type 'ns2:uploadWjzpResponse': */
struct SOAP_CMAC ns2__uploadWjzpResponse {
      public:
        /** Required element 'uploadWjzpReturn' of XML schema type 'xsd:string' */
        std::wstring _uploadWjzpReturn;
      public:
        /** Return unique type id SOAP_TYPE_ns2__uploadWjzpResponse */
        long soap_type() const { return SOAP_TYPE_ns2__uploadWjzpResponse; }
        /** Constructor with member initializations */
        ns2__uploadWjzpResponse() : _uploadWjzpReturn() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__uploadWjzpResponse * SOAP_FMAC2 soap_instantiate_ns2__uploadWjzpResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:811 */
#ifndef SOAP_TYPE_ns2__uploadWjzp
#define SOAP_TYPE_ns2__uploadWjzp (43)
/* complex XML schema type 'ns2:uploadWjzp': */
struct SOAP_CMAC ns2__uploadWjzp {
      public:
        /** Required element 'imgStr' of XML schema type 'xsd:string' */
        std::wstring _imgStr;
      public:
        /** Return unique type id SOAP_TYPE_ns2__uploadWjzp */
        long soap_type() const { return SOAP_TYPE_ns2__uploadWjzp; }
        /** Constructor with member initializations */
        ns2__uploadWjzp() : _imgStr() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__uploadWjzp * SOAP_FMAC2 soap_instantiate_ns2__uploadWjzp(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:887 */
#ifndef SOAP_TYPE_ns2__queryObjectOutResponse
#define SOAP_TYPE_ns2__queryObjectOutResponse (45)
/* complex XML schema type 'ns2:queryObjectOutResponse': */
struct SOAP_CMAC ns2__queryObjectOutResponse {
      public:
        /** Required element 'queryObjectOutReturn' of XML schema type 'xsd:string' */
        std::wstring _queryObjectOutReturn;
      public:
        /** Return unique type id SOAP_TYPE_ns2__queryObjectOutResponse */
        long soap_type() const { return SOAP_TYPE_ns2__queryObjectOutResponse; }
        /** Constructor with member initializations */
        ns2__queryObjectOutResponse() : _queryObjectOutReturn() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__queryObjectOutResponse * SOAP_FMAC2 soap_instantiate_ns2__queryObjectOutResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:887 */
#ifndef SOAP_TYPE_ns2__queryObjectOut
#define SOAP_TYPE_ns2__queryObjectOut (46)
/* complex XML schema type 'ns2:queryObjectOut': */
struct SOAP_CMAC ns2__queryObjectOut {
      public:
        /** Required element 'xtlb' of XML schema type 'xsd:string' */
        std::wstring _xtlb;
        /** Required element 'jkxlh' of XML schema type 'xsd:string' */
        std::wstring _jkxlh;
        /** Required element 'jkid' of XML schema type 'xsd:string' */
        std::wstring _jkid;
        /** Required element 'QueryXmlDoc' of XML schema type 'xsd:string' */
        std::wstring _QueryXmlDoc;
      public:
        /** Return unique type id SOAP_TYPE_ns2__queryObjectOut */
        long soap_type() const { return SOAP_TYPE_ns2__queryObjectOut; }
        /** Constructor with member initializations */
        ns2__queryObjectOut() : _xtlb(), _jkxlh(), _jkid(), _QueryXmlDoc() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns2__queryObjectOut * SOAP_FMAC2 soap_instantiate_ns2__queryObjectOut(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* jcjkService.h:948 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (47)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* jcjkService.h:948 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (48)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* jcjkService.h:948 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (50)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* jcjkService.h:948 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (53)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* jcjkService.h:948 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (54)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* unsigned char has binding name 'unsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (12)
#endif

/* unsigned int has binding name 'unsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (11)
#endif

/* std::wstring has binding name 'std__wstring' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__wstring
#define SOAP_TYPE_std__wstring (15)
#endif

/* ArrayOf_USCOREsoapenc_USCOREstring has binding name 'ArrayOf_USCOREsoapenc_USCOREstring' for type 'xsd:string' */
#ifndef SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring
#define SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring (14)
#endif

/* SOAP_ENC__base64Binary has binding name 'SOAP_ENC__base64Binary' for type 'SOAP-ENC:base64Binary' */
#ifndef SOAP_TYPE_SOAP_ENC__base64Binary
#define SOAP_TYPE_SOAP_ENC__base64Binary (10)
#endif

/* SOAP_ENC__Array has binding name 'SOAP_ENC__Array' for type 'SOAP-ENC:Array' */
#ifndef SOAP_TYPE_SOAP_ENC__Array
#define SOAP_TYPE_SOAP_ENC__Array (8)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (54)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (53)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (50)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (48)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (47)
#endif

/* struct ns2__queryObjectOut has binding name 'ns2__queryObjectOut' for type 'ns2:queryObjectOut' */
#ifndef SOAP_TYPE_ns2__queryObjectOut
#define SOAP_TYPE_ns2__queryObjectOut (46)
#endif

/* struct ns2__queryObjectOutResponse has binding name 'ns2__queryObjectOutResponse' for type 'ns2:queryObjectOutResponse' */
#ifndef SOAP_TYPE_ns2__queryObjectOutResponse
#define SOAP_TYPE_ns2__queryObjectOutResponse (45)
#endif

/* struct ns2__uploadWjzp has binding name 'ns2__uploadWjzp' for type 'ns2:uploadWjzp' */
#ifndef SOAP_TYPE_ns2__uploadWjzp
#define SOAP_TYPE_ns2__uploadWjzp (43)
#endif

/* struct ns2__uploadWjzpResponse has binding name 'ns2__uploadWjzpResponse' for type 'ns2:uploadWjzpResponse' */
#ifndef SOAP_TYPE_ns2__uploadWjzpResponse
#define SOAP_TYPE_ns2__uploadWjzpResponse (42)
#endif

/* struct ns2__getZpgwcs has binding name 'ns2__getZpgwcs' for type 'ns2:getZpgwcs' */
#ifndef SOAP_TYPE_ns2__getZpgwcs
#define SOAP_TYPE_ns2__getZpgwcs (40)
#endif

/* struct ns2__getZpgwcsResponse has binding name 'ns2__getZpgwcsResponse' for type 'ns2:getZpgwcsResponse' */
#ifndef SOAP_TYPE_ns2__getZpgwcsResponse
#define SOAP_TYPE_ns2__getZpgwcsResponse (39)
#endif

/* struct ns2__uploadFile has binding name 'ns2__uploadFile' for type 'ns2:uploadFile' */
#ifndef SOAP_TYPE_ns2__uploadFile
#define SOAP_TYPE_ns2__uploadFile (37)
#endif

/* struct ns2__uploadFileResponse has binding name 'ns2__uploadFileResponse' for type 'ns2:uploadFileResponse' */
#ifndef SOAP_TYPE_ns2__uploadFileResponse
#define SOAP_TYPE_ns2__uploadFileResponse (36)
#endif

/* struct ns2__writeObjectOut has binding name 'ns2__writeObjectOut' for type 'ns2:writeObjectOut' */
#ifndef SOAP_TYPE_ns2__writeObjectOut
#define SOAP_TYPE_ns2__writeObjectOut (34)
#endif

/* struct ns2__writeObjectOutResponse has binding name 'ns2__writeObjectOutResponse' for type 'ns2:writeObjectOutResponse' */
#ifndef SOAP_TYPE_ns2__writeObjectOutResponse
#define SOAP_TYPE_ns2__writeObjectOutResponse (33)
#endif

/* struct ns2__checkNull has binding name 'ns2__checkNull' for type 'ns2:checkNull' */
#ifndef SOAP_TYPE_ns2__checkNull
#define SOAP_TYPE_ns2__checkNull (30)
#endif

/* struct ns2__checkNullResponse has binding name 'ns2__checkNullResponse' for type 'ns2:checkNullResponse' */
#ifndef SOAP_TYPE_ns2__checkNullResponse
#define SOAP_TYPE_ns2__checkNullResponse (27)
#endif

/* struct ns2__init has binding name 'ns2__init' for type 'ns2:init' */
#ifndef SOAP_TYPE_ns2__init
#define SOAP_TYPE_ns2__init (26)
#endif

/* struct ns2__initResponse has binding name 'ns2__initResponse' for type 'ns2:initResponse' */
#ifndef SOAP_TYPE_ns2__initResponse
#define SOAP_TYPE_ns2__initResponse (23)
#endif

/* struct ns2__main has binding name 'ns2__main' for type 'ns2:main' */
#ifndef SOAP_TYPE_ns2__main
#define SOAP_TYPE_ns2__main (22)
#endif

/* struct ns2__mainResponse has binding name 'ns2__mainResponse' for type 'ns2:mainResponse' */
#ifndef SOAP_TYPE_ns2__mainResponse
#define SOAP_TYPE_ns2__mainResponse (18)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (56)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (55)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (49)
#endif

/* ArrayOf_USCOREsoapenc_USCOREstring * has binding name 'PointerToArrayOf_USCOREsoapenc_USCOREstring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerToArrayOf_USCOREsoapenc_USCOREstring
#define SOAP_TYPE_PointerToArrayOf_USCOREsoapenc_USCOREstring (19)
#endif

/* std::wstring * has binding name 'PointerTostd__wstring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostd__wstring
#define SOAP_TYPE_PointerTostd__wstring (16)
#endif

/* unsigned char * has binding name 'PointerTounsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (13)
#endif

/* char ** has binding name 'PointerTo_XML' for type '' */
#ifndef SOAP_TYPE_PointerTo_XML
#define SOAP_TYPE_PointerTo_XML (9)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
