/* soapStub.h
   Generated by gSOAP 2.7.17 from WebService.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_WS1__queryObjectOutResponse
#define SOAP_TYPE_WS1__queryObjectOutResponse (11)
/* WS1:queryObjectOutResponse */
struct WS1__queryObjectOutResponse
{
public:
	std::wstring _queryObjectOutReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS1__queryObjectOut
#define SOAP_TYPE_WS1__queryObjectOut (12)
/* WS1:queryObjectOut */
struct WS1__queryObjectOut
{
public:
	std::wstring _xtlb;	/* required element of type xsd:string */
	std::wstring _jkxlh;	/* required element of type xsd:string */
	std::wstring _jkid;	/* required element of type xsd:string */
	std::wstring _yhbz;	/* required element of type xsd:string */
	std::wstring _dwmc;	/* required element of type xsd:string */
	std::wstring _dwjgdm;	/* required element of type xsd:string */
	std::wstring _yhxm;	/* required element of type xsd:string */
	std::wstring _zdbs;	/* required element of type xsd:string */
	std::wstring _UTF8XmlDoc;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS1__queryObjectOutNewResponse
#define SOAP_TYPE_WS1__queryObjectOutNewResponse (14)
/* WS1:queryObjectOutNewResponse */
struct WS1__queryObjectOutNewResponse
{
public:
	std::wstring _queryObjectOutNewReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS1__queryObjectOutNew
#define SOAP_TYPE_WS1__queryObjectOutNew (15)
/* WS1:queryObjectOutNew */
struct WS1__queryObjectOutNew
{
public:
	std::wstring _xtlb;	/* required element of type xsd:string */
	std::wstring _jkxlh;	/* required element of type xsd:string */
	std::wstring _jkid;	/* required element of type xsd:string */
	std::wstring _cjsqbh;	/* required element of type xsd:string */
	std::wstring _dwjgdm;	/* required element of type xsd:string */
	std::wstring _dwmc;	/* required element of type xsd:string */
	std::wstring _yhbz;	/* required element of type xsd:string */
	std::wstring _yhxm;	/* required element of type xsd:string */
	std::wstring _zdbs;	/* required element of type xsd:string */
	std::wstring _UTF8XmlDoc;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS1__writeObjectOutResponse
#define SOAP_TYPE_WS1__writeObjectOutResponse (17)
/* WS1:writeObjectOutResponse */
struct WS1__writeObjectOutResponse
{
public:
	std::wstring _writeObjectOutReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS1__writeObjectOut
#define SOAP_TYPE_WS1__writeObjectOut (18)
/* WS1:writeObjectOut */
struct WS1__writeObjectOut
{
public:
	std::wstring _xtlb;	/* required element of type xsd:string */
	std::wstring _jkxlh;	/* required element of type xsd:string */
	std::wstring _jkid;	/* required element of type xsd:string */
	std::wstring _yhbz;	/* required element of type xsd:string */
	std::wstring _dwmc;	/* required element of type xsd:string */
	std::wstring _dwjgdm;	/* required element of type xsd:string */
	std::wstring _yhxm;	/* required element of type xsd:string */
	std::wstring _zdbs;	/* required element of type xsd:string */
	std::wstring _UTF8XmlDoc;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS1__writeObjectOutNewResponse
#define SOAP_TYPE_WS1__writeObjectOutNewResponse (20)
/* WS1:writeObjectOutNewResponse */
struct WS1__writeObjectOutNewResponse
{
public:
	std::wstring _writeObjectOutNewReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS1__writeObjectOutNew
#define SOAP_TYPE_WS1__writeObjectOutNew (21)
/* WS1:writeObjectOutNew */
struct WS1__writeObjectOutNew
{
public:
	std::wstring _xtlb;	/* required element of type xsd:string */
	std::wstring _jkxlh;	/* required element of type xsd:string */
	std::wstring _jkid;	/* required element of type xsd:string */
	std::wstring _cjsqbh;	/* required element of type xsd:string */
	std::wstring _dwjgdm;	/* required element of type xsd:string */
	std::wstring _dwmc;	/* required element of type xsd:string */
	std::wstring _yhbz;	/* required element of type xsd:string */
	std::wstring _yhxm;	/* required element of type xsd:string */
	std::wstring _zdbs;	/* required element of type xsd:string */
	std::wstring _UTF8XmlDoc;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (28)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (29)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_WS1__queryObjectOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::wstring _xtlb, std::wstring _jkxlh, std::wstring _jkid, std::wstring _yhbz, std::wstring _dwmc, std::wstring _dwjgdm, std::wstring _yhxm, std::wstring _zdbs, std::wstring _UTF8XmlDoc, std::wstring &_queryObjectOutReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_WS1__queryObjectOutNew(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::wstring _xtlb, std::wstring _jkxlh, std::wstring _jkid, std::wstring _cjsqbh, std::wstring _dwjgdm, std::wstring _dwmc, std::wstring _yhbz, std::wstring _yhxm, std::wstring _zdbs, std::wstring _UTF8XmlDoc, std::wstring &_queryObjectOutNewReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_WS1__writeObjectOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::wstring _xtlb, std::wstring _jkxlh, std::wstring _jkid, std::wstring _yhbz, std::wstring _dwmc, std::wstring _dwjgdm, std::wstring _yhxm, std::wstring _zdbs, std::wstring _UTF8XmlDoc, std::wstring &_writeObjectOutReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_WS1__writeObjectOutNew(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::wstring _xtlb, std::wstring _jkxlh, std::wstring _jkid, std::wstring _cjsqbh, std::wstring _dwjgdm, std::wstring _dwmc, std::wstring _yhbz, std::wstring _yhxm, std::wstring _zdbs, std::wstring _UTF8XmlDoc, std::wstring &_writeObjectOutNewReturn);

#endif

/* End of soapStub.h */
